name: CI Pipeline

on:
  push:
    branches:
      - dev
      - prod
  pull_request:
    branches:
      - dev
      - prod

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9  # Adjust to match your project's Python version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyspark pytest pytest-html pytest-cov

    # Step 4: Run unit tests and save results
    - name: Run tests
      run: |
        mkdir -p tests/results
        pytest tests/ --maxfail=5 --disable-warnings \
          --cov=scripts \
          --cov-report=html:tests/results/cov_html \
          --junitxml=tests/results/test_results.xml \
          > tests/results/test_results.txt

    # Step 5: Upload test results (optional)
    - name: Upload test results artifact
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: tests/results/
